FROM openjdk:17
LABEL authors="saadahmedscse"
EXPOSE 8084
ADD target/vendor-voyage-product-service.jar vendor-voyage-product-service.jar
ENTRYPOINT ["java", "-jar", "/vendor-voyage-product-service.jar"]